### ISSUE TITLE
idea2020.1.1不支持

### ISSUE THREAD

**Issue by chenhaoxiang** [jadepeng/idea-rainbow-fart#3]
报错：incompatible （since build 201.7846 > IU-201.7223.91）

**Comment by chenhaoxiang** [comment]
异常图片地址：https://raw.githubusercontent.com/chenhaoxiang/github-images/master/2020/07/06/ESLiJW.jpg

**Comment by Gee-Gao** [comment]
idea2020.1.2  自定义没有效果

**Comment by jadepeng** [comment]
下载最新的rainbow-fart-1.0.4new.zip
