### ISSUE TITLE
Fart setttings 一直显示loading

### ISSUE THREAD

**Issue by haojinyao** [jadepeng/idea-rainbow-fart#5]
idea版本是2019.3，不知道为什么设置面板一直loading...

**Comment by liiitleboy** [comment]
俺也一样

**Comment by jasonchen-why** [comment]
一直loading的原因是缺少jar包：commons-lang3-3.1.jar。
方案：把commons-lang3-3.1.jar文件拷贝到文件夹..\plugins\rainbow-fart\lib\下即可

**Comment by liiitleboy** [comment]
thanks



hanyu13@58.com
 
发件人： jasonchen-why
发送时间： 2020-07-23 17:43
收件人： jadepeng/idea-rainbow-fart
抄送： liiitleboy; Comment
主题： Re: [jadepeng/idea-rainbow-fart] Fart setttings 一直显示loading (#5)
一直loading的原因是缺少jar包：commons-lang3-3.1.jar。
方案：把commons-lang3-3.1.jar文件拷贝到文件夹..\plugins\rainbow-fart\lib\下即可

**Comment by haojinyao** [comment]
解决了，蟹蟹

**Comment by jasonchen-why** [comment]
> 解决了，蟹蟹

不用客气
